# Generated by Django 4.2.16 on 2024-11-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_cargo_alter_contato_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='area_metropolitana',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='É área metropolitana?'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='capital',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='É capital?'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='mais_de_80_mil_hab',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Tem mais de 80 mil habitantes?'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='regiao_metropolitana',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Pertence à região metropolitana?'),
        ),
    ]
