# Generated by Django 4.2.16 on 2024-11-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_municipio_area_metropolitana_municipio_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
