# Generated by Django 4.2.16 on 2024-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_contato_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='nome_metropolitana',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='nome_regiao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
