# Generated by Django 4.2.16 on 2024-11-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_municipio_nome_metropolitana_municipio_nome_regiao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='area_metropolitana',
        ),
    ]
