# Generated by Django 5.2.4 on 2025-07-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_municipio_area_metropolitana'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='adimplente',
            field=models.BooleanField(default=False, verbose_name='Município Adimplente'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.municipio'),
        ),
    ]
