# Generated by Django 5.2.4 on 2025-07-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_municipio_adimplente_alter_contato_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='municipio',
            field=models.ForeignKey(default=5571, on_delete=django.db.models.deletion.PROTECT, to='base.municipio'),
            preserve_default=False,
        ),
    ]
